### PR TITLE
Fix bug in processor.coffee

### PR DESCRIPTION
**Pull request by jasonkuhrt**
This is a naive proposal for fixing a bug I found in my research documented at https://github.com/postcss/postcss-import/issues/19#issuecomment-71777987. Also it may be that the bug is with `postcss-import`. But technically this will make the problem go away, I just don't know why it happened in the first place. Very likely @ai can explain the issue and offer a better solution.

### CODE REVIEW

**Comment by MoOx** [comment]
This seems to be related the postcss method that postcss-import uses (insertBefore()).
Ref https://github.com/postcss/postcss/issues/171
It seems .before property has been dropped and make bring this bug into autoprefixer.

**Comment by ai** [comment]
Thanks! Here is a better way: b4c81bd

**Comment by jasonkuhrt** [comment]
@ai Ah, yep better : )

@ai @MoOx I'm trying to understand why this can even happen. The test case I created that unearths the error doesn't even have invalid CSS or anything https://github.com/postcss/postcss-import/issues/19#issuecomment-71777987. While, yes, we've fixed the stupid bug (property read on `undefined`) what about the fact that this is possible? Is this a good design? Just curious.

@ai @MoOx Also shouldn't we commit my test case (https://github.com/postcss/postcss-import/issues/19#issuecomment-71777987) somewhere? It involves three repos so I'm not sure where we want to track the bug fix but it sounds like autoprefixer. Except commiting `postcss-import` and `postcss` to `dev-deps` of `autoprefixer` just for a test seems a bit... weird.

**Comment by MoOx** [comment]
It seems @ai just have a method to prevent this error. So since it have updated the place where the bug came from, "this should be ok".

That being said, for me, it clearly related to this "issue" https://github.com/postcss/postcss/issues/171

**Comment by ai** [comment]
Yeap, we should add test. But we need to add tests without `postcss-import` to make them independent :).

**Comment by jasonkuhrt** [comment]
@ai Ok, maybe you can figure out a simpler way to "trigger" the bug. That was the simplest test case I could find haha.

**Pull request merged**
