### PR TITLE
npm build script

### PR DESCRIPTION
**Pull request by joshgillies**

### CODE REVIEW

**Comment by ai** [comment]
Seems like it doesn’t work :(.

**Comment by ai** [comment]
I reversed merge

**Comment by lydell** [comment]
@ai Just got a funny feeling thinking that you may have run `npm build` instead of `npm run build`. I may be wrong, though …

**Comment by ai** [comment]
I run first one :-). But I still don't know why we need a build shortcut if we can just write `gulp build` :-).

**Comment by joshgillies** [comment]
Basically aliasing it in this way does away with needing Gulp installed via `npm install gulp -g` and as a result in easier on boarding of new collaborators, and you get to version it inline with the code it's been developed against.

Granted in isolation the alias `"build: "gulp build"` doesn't seem like much, but when paired with another script like `pre-publish` you get yourself a pretty nice development/release workflow with npm. Just a thought anyway. :)

**Comment by lydell** [comment]
Ah, that reminds me of a PR I got for another project which was also about not needing install gulp globally to be able to build. We ended up adding [this line](https://github.com/akhodakivskiy/VimFx/blob/c1bc315c86f2d00ac2f719a1b6a7142002b2ddd0/package.json#L11) to package.json. Then you're able run _any_ gulp command by typing `npm run gulp -- any_command_here`. Pretty nice.

**Comment by joshgillies** [comment]
That's actually a pretty sound solution! Thanks for the heads up :)

**Comment by ai** [comment]
I use different solution: https://github.com/ai/environment/blob/master/zshrc#L53

As result I just can write: `n gulp build` to execute `gulp` from current `node_modules/.bin/`.

**Comment by joshgillies** [comment]
@ai that's actually pretty excellent! Thanks! :+1:

**Comment by lydell** [comment]
I add `./node_modules/.bin` to `$PATH` ;)

**Pull request merged**
