### PR TITLE
Corrected example in the README.

### PR DESCRIPTION
**Pull request by ben-eb**

### CODE REVIEW

**Comment by ai** [comment]
Your commit is correct, but `autoprefixer-core` will be depreacted in next main release

**Comment by ben-eb** [comment]
Didn't realise, thanks. :smiley:

**Comment by stevemao** [comment]
Where can I get more info on the deprecation?

**Comment by ai** [comment]
@stevemao I will write about it in every release notes.

Current plan is:

* **5.2**: `autoprefixer` CLI and `autoprefixer#process()` will be deprecated.
* **6.0**: `autoprefixer-core` will be renamed to `autoprefixer`.

But seems like 6.0 release will be only in winter.

**Pull request closed without merging**
